<?php
/**
 * BundleTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SendOwl API
 *
 * The SendOwl API allows third party applications to access and update data associated with customer accounts.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.57
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * BundleTest Class Doc Comment
 *
 * @category    Class
 * @description Bundle
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class BundleTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Bundle"
     */
    public function testBundle()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "category"
     */
    public function testPropertyCategory()
    {
    }

    /**
     * Test attribute "subcategory"
     */
    public function testPropertySubcategory()
    {
    }

    /**
     * Test attribute "price"
     */
    public function testPropertyPrice()
    {
    }

    /**
     * Test attribute "custom_field"
     */
    public function testPropertyCustomField()
    {
    }

    /**
     * Test attribute "components"
     */
    public function testPropertyComponents()
    {
    }

    /**
     * Test attribute "shopify_variant_id"
     */
    public function testPropertyShopifyVariantId()
    {
    }

    /**
     * Test attribute "override_currency_code"
     */
    public function testPropertyOverrideCurrencyCode()
    {
    }

    /**
     * Test attribute "currency_code"
     */
    public function testPropertyCurrencyCode()
    {
    }

    /**
     * Test attribute "product_image_url"
     */
    public function testPropertyProductImageUrl()
    {
    }

    /**
     * Test attribute "instant_buy_url"
     */
    public function testPropertyInstantBuyUrl()
    {
    }

    /**
     * Test attribute "add_to_cart_url"
     */
    public function testPropertyAddToCartUrl()
    {
    }

    /**
     * Test attribute "sales_page_url"
     */
    public function testPropertySalesPageUrl()
    {
    }

    /**
     * Test attribute "price_is_minimum"
     */
    public function testPropertyPriceIsMinimum()
    {
    }

    /**
     * Test attribute "limit_to_single_qty_in_cart"
     */
    public function testPropertyLimitToSingleQtyInCart()
    {
    }

    /**
     * Test attribute "affiliate_sellable"
     */
    public function testPropertyAffiliateSellable()
    {
    }

    /**
     * Test attribute "commission_rate"
     */
    public function testPropertyCommissionRate()
    {
    }

    /**
     * Test attribute "access_all_products"
     */
    public function testPropertyAccessAllProducts()
    {
    }

    /**
     * Test attribute "access_after_order_creation"
     */
    public function testPropertyAccessAfterOrderCreation()
    {
    }

    /**
     * Test attribute "access_after_order_creation_includes_previous"
     */
    public function testPropertyAccessAfterOrderCreationIncludesPrevious()
    {
    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
    }

    /**
     * Test attribute "updated_at"
     */
    public function testPropertyUpdatedAt()
    {
    }
}
