<?php
/**
 * OrderTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SendOwl API
 *
 * The SendOwl API allows third party applications to access and update data associated with customer accounts.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.57
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * OrderTest Class Doc Comment
 *
 * @category    Class
 * @description Order
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OrderTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Order"
     */
    public function testOrder()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "state"
     */
    public function testPropertyState()
    {
    }

    /**
     * Test attribute "gateway"
     */
    public function testPropertyGateway()
    {
    }

    /**
     * Test attribute "payment_method"
     */
    public function testPropertyPaymentMethod()
    {
    }

    /**
     * Test attribute "buyer_email"
     */
    public function testPropertyBuyerEmail()
    {
    }

    /**
     * Test attribute "paypal_email"
     */
    public function testPropertyPaypalEmail()
    {
    }

    /**
     * Test attribute "buyer_name"
     */
    public function testPropertyBuyerName()
    {
    }

    /**
     * Test attribute "giftee_name"
     */
    public function testPropertyGifteeName()
    {
    }

    /**
     * Test attribute "giftee_email"
     */
    public function testPropertyGifteeEmail()
    {
    }

    /**
     * Test attribute "gift_deliver_at"
     */
    public function testPropertyGiftDeliverAt()
    {
    }

    /**
     * Test attribute "business_name"
     */
    public function testPropertyBusinessName()
    {
    }

    /**
     * Test attribute "business_vat_number"
     */
    public function testPropertyBusinessVatNumber()
    {
    }

    /**
     * Test attribute "shipping_address1"
     */
    public function testPropertyShippingAddress1()
    {
    }

    /**
     * Test attribute "shipping_address2"
     */
    public function testPropertyShippingAddress2()
    {
    }

    /**
     * Test attribute "shipping_city"
     */
    public function testPropertyShippingCity()
    {
    }

    /**
     * Test attribute "shipping_region"
     */
    public function testPropertyShippingRegion()
    {
    }

    /**
     * Test attribute "shipping_postcode"
     */
    public function testPropertyShippingPostcode()
    {
    }

    /**
     * Test attribute "shipping_country"
     */
    public function testPropertyShippingCountry()
    {
    }

    /**
     * Test attribute "billing_address1"
     */
    public function testPropertyBillingAddress1()
    {
    }

    /**
     * Test attribute "billing_address2"
     */
    public function testPropertyBillingAddress2()
    {
    }

    /**
     * Test attribute "billing_city"
     */
    public function testPropertyBillingCity()
    {
    }

    /**
     * Test attribute "billing_region"
     */
    public function testPropertyBillingRegion()
    {
    }

    /**
     * Test attribute "billing_postcode"
     */
    public function testPropertyBillingPostcode()
    {
    }

    /**
     * Test attribute "billing_country"
     */
    public function testPropertyBillingCountry()
    {
    }

    /**
     * Test attribute "eu_resolved_country"
     */
    public function testPropertyEuResolvedCountry()
    {
    }

    /**
     * Test attribute "buyer_ip_address"
     */
    public function testPropertyBuyerIpAddress()
    {
    }

    /**
     * Test attribute "settled_currency"
     */
    public function testPropertySettledCurrency()
    {
    }

    /**
     * Test attribute "settled_gross"
     */
    public function testPropertySettledGross()
    {
    }

    /**
     * Test attribute "settled_gateway_fee"
     */
    public function testPropertySettledGatewayFee()
    {
    }

    /**
     * Test attribute "settled_tax"
     */
    public function testPropertySettledTax()
    {
    }

    /**
     * Test attribute "accounted_tax"
     */
    public function testPropertyAccountedTax()
    {
    }

    /**
     * Test attribute "settled_handling"
     */
    public function testPropertySettledHandling()
    {
    }

    /**
     * Test attribute "settled_shipping"
     */
    public function testPropertySettledShipping()
    {
    }

    /**
     * Test attribute "settled_affiliate_fee"
     */
    public function testPropertySettledAffiliateFee()
    {
    }

    /**
     * Test attribute "discount"
     */
    public function testPropertyDiscount()
    {
    }

    /**
     * Test attribute "price_at_checkout"
     */
    public function testPropertyPriceAtCheckout()
    {
    }

    /**
     * Test attribute "refunded"
     */
    public function testPropertyRefunded()
    {
    }

    /**
     * Test attribute "affiliate_system"
     */
    public function testPropertyAffiliateSystem()
    {
    }

    /**
     * Test attribute "can_market_to_buyer"
     */
    public function testPropertyCanMarketToBuyer()
    {
    }

    /**
     * Test attribute "gateway_transaction_ids"
     */
    public function testPropertyGatewayTransactionIds()
    {
    }

    /**
     * Test attribute "order_name"
     */
    public function testPropertyOrderName()
    {
    }

    /**
     * Test attribute "download_url"
     */
    public function testPropertyDownloadUrl()
    {
    }

    /**
     * Test attribute "subscription_management_url"
     */
    public function testPropertySubscriptionManagementUrl()
    {
    }

    /**
     * Test attribute "valid_until"
     */
    public function testPropertyValidUntil()
    {
    }

    /**
     * Test attribute "download_attempts"
     */
    public function testPropertyDownloadAttempts()
    {
    }

    /**
     * Test attribute "access_allowed"
     */
    public function testPropertyAccessAllowed()
    {
    }

    /**
     * Test attribute "dispatched_at"
     */
    public function testPropertyDispatchedAt()
    {
    }

    /**
     * Test attribute "tag"
     */
    public function testPropertyTag()
    {
    }

    /**
     * Test attribute "order_custom_checkout_fields"
     */
    public function testPropertyOrderCustomCheckoutFields()
    {
    }

    /**
     * Test attribute "download_items"
     */
    public function testPropertyDownloadItems()
    {
    }

    /**
     * Test attribute "downloads"
     */
    public function testPropertyDownloads()
    {
    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
    }

    /**
     * Test attribute "updated_at"
     */
    public function testPropertyUpdatedAt()
    {
    }
}
