<?php
/**
 * DefaultApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SendOwl API
 *
 * The SendOwl API allows third party applications to access and update data associated with customer accounts.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.57
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DefaultApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createBundle
     *
     * Create a new bundle.
     *
     */
    public function testCreateBundle()
    {
    }

    /**
     * Test case for deleteBundle
     *
     * Delete a bundle.
     *
     */
    public function testDeleteBundle()
    {
    }

    /**
     * Test case for deleteOrder
     *
     * Delete an order.
     *
     */
    public function testDeleteOrder()
    {
    }

    /**
     * Test case for getBundle
     *
     * Get a specific bundle.
     *
     */
    public function testGetBundle()
    {
    }

    /**
     * Test case for getBundles
     *
     * List all bundles.
     *
     */
    public function testGetBundles()
    {
    }

    /**
     * Test case for getOrder
     *
     * Get a specific order.
     *
     */
    public function testGetOrder()
    {
    }

    /**
     * Test case for getOrders
     *
     * List all orders.
     *
     */
    public function testGetOrders()
    {
    }

    /**
     * Test case for refundOrder
     *
     * Refund an order.
     *
     */
    public function testRefundOrder()
    {
    }

    /**
     * Test case for resendOrderEmail
     *
     * Resend order emails.
     *
     */
    public function testResendOrderEmail()
    {
    }

    /**
     * Test case for searchOrders
     *
     * Search orders.
     *
     */
    public function testSearchOrders()
    {
    }

    /**
     * Test case for updateBundle
     *
     * Update a bundle.
     *
     */
    public function testUpdateBundle()
    {
    }

    /**
     * Test case for updateOrder
     *
     * Update an order.
     *
     */
    public function testUpdateOrder()
    {
    }
}
